return {
  require("user.plugins.bufferline"),
  require("user.plugins.blink"),
  require("user.plugins.catppuccin"),
  require("user.plugins.ccc"),
  require("user.plugins.crates"),
  require("user.plugins.dap"),
  require("user.plugins.illuminate"),
  require("user.plugins.inlay-hint"),
  require("user.plugins.lspconfig"),
  require("user.plugins.lualine"),
  require("user.plugins.markdown"),
  require("user.plugins.mason"),
  require("user.plugins.mini"),
  require("user.plugins.noice"),
  require("user.plugins.rainbowcsv"),
  require("user.plugins.rustaceanvim"),
  require("user.plugins.snacks"),
  require("user.plugins.todo-comments"),
  require("user.plugins.tokyonight"),
  require("user.plugins.treesitter"),
  require("user.plugins.whichkey"),
}

